import "./globals.css";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import { Header, Footer } from "@/components";
import StyledComponentsRegistry from "../lib/AntdRegistry";

export const metadata = {
  title: "Nutritionist",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-screen">
      <body className={`${inter.className} relative h-full`}>
        <StyledComponentsRegistry>
          <main className="relative flex min-h-screen flex-col gap-10">
            <Header />
            <div className="flex-1 flex-grow">{children}</div>
            <Footer />
          </main>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
