import "./globals.css";
import { Inter } from "next/font/google";
import NavigationBar from "@/components/NavigationBar";
import {AuthProvider} from "@/components/SessionProviders";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Obesity Controller",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-screen">
      <body className={inter.className}>
        <AuthProvider>
          <NavigationBar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
