import "./globals.css";
import { Inter } from "next/font/google";
import NavigationBar from "@/components/NavigationBar";
import { SessionProvider } from "@/components/Session";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Obesity Controller",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-screen">
      <SessionProvider>
        <body className={inter.className}>
          <NavigationBar />
          {children}
        </body>
      </SessionProvider>
    </html>
  );
}
